name: Lighthouse CI

on:
  workflow_run:
    workflows: [Deploy]
    types: [completed]

env:
  APP_URL: https://kubosho-wsh-2026.fly.dev

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Initialize database
        run: |
          curl -sf -X POST "$APP_URL/api/v1/initialize" > /dev/null
          echo "Database initialized"

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@2f8dda6cf4de7d73b29853c3f29e73a01e297bd8
        with:
          configPath: ./lighthouserc.cjs
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          LHCI_BASE_URL: https://kubosho-wsh-2026.fly.dev
